spring.application.name=VentaBoletas2303
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.show-sql=true
spring.datasource.url=jdbc:postgresql://dpg-d710e5dm5p6s738pc6j0-a.oregon-postgres.render.com/dbventaboletas
spring.datasource.username=karmenyrafa
spring.datasource.password=yvHRVl2THYhpNqIdJKH92IHmLI37JoN7
